name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Decode SSH private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > id_ed25519

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/minecraft-disc-bot:latest
        build-args: |
          PORT=${{ secrets.PORT }}
          HOST=${{ secrets.HOST }}

    - name: Deploy Docker container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/minecraft-disc-bot:latest
        docker stop minecraft-disc-bot || true
        docker rm minecraft-disc-bot || true
        docker run -d --restart=unless-stopped --name minecraft-disc-bot \
          -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
          -e USERNAME=${{ secrets.USERNAME }} \
          -e HOST=${{ secrets.HOST }} \
          -e PORT=${{ secrets.PORT }} \
          -e SCRIPTS_PATH=${{ secrets.SCRIPTS_PATH }} \
          -e MINECRAFT_LOGS_PATH=${{ secrets.MINECRAFT_LOGS_PATH }} \
          -v ${{ secrets.DATA_PATH }}:/usr/src/app/data \
          ${{ secrets.DOCKER_USERNAME }}/minecraft-disc-bot:latest
